name: Count LOC
on: push
jobs:
  count:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Count lines
        env:
          GH_TOKEN: ${{ secrets.LOC_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          # Install jq
          sudo apt-get update && sudo apt-get install -y jq
          
          # Setup
          total_lines=0
          repo_count=0
          
          echo "Fetching repositories..."
          
          # Get all non-forked repos using gh CLI which handles pagination
          repos=$(gh api /user/repos --paginate -q '.[] | select(.fork == false) | .name')
          
          for repo in $repos; do
            echo "Processing $repo..."
            
            # Get language statistics
            lang_data=$(gh api "/repos/murr2k/$repo/languages" 2>/dev/null || echo "{}")
            
            # Sum bytes across all languages
            bytes=$(echo "$lang_data" | jq '[.[]] | add // 0')
            
            # Convert bytes to lines (average ~35 bytes per line)
            lines=$((bytes / 35))
            total_lines=$((total_lines + lines))
            repo_count=$((repo_count + 1))
            
            echo "  $repo: $lines lines ($bytes bytes)"
          done
          
          echo "Total: $total_lines lines in $repo_count repositories"
          
          # Format
          if [ $total_lines -ge 1000000000 ]; then
            formatted="$((total_lines/1000000000))B+"
          elif [ $total_lines -ge 1000000 ]; then
            formatted="$((total_lines/1000000))M+"
          elif [ $total_lines -ge 1000 ]; then
            formatted="$((total_lines/1000))K+"
          else
            formatted="${total_lines}+"
          fi
          
          # Update stats
          cat > stats-simple.json << EOF
{
  "lines_of_code": $total_lines,
  "repositories": $repo_count,
  "last_updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "formatted": "$formatted"
}
EOF
          
      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats-simple.json
          git diff --staged --quiet || (git commit -m "📊 Update LOC stats" && git push)