name: Update LOC Stats

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  count:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup
        run: |
          # Get latest tokei release
          TOKEI_VERSION=$(curl -s https://api.github.com/repos/XAMPPRocky/tokei/releases/latest | grep '"tag_name"' | cut -d'"' -f4 | sed 's/^v//')
          echo "Installing tokei version $TOKEI_VERSION"
          
          # Download and install
          wget -q "https://github.com/XAMPPRocky/tokei/releases/download/v${TOKEI_VERSION}/tokei-x86_64-unknown-linux-gnu.tar.gz" || {
            echo "Failed to download tokei"
            exit 1
          }
          tar xf tokei-x86_64-unknown-linux-gnu.tar.gz
          sudo mv tokei /usr/local/bin/
          rm tokei-x86_64-unknown-linux-gnu.tar.gz
          
          # Verify installation
          tokei --version
          
      - name: Count LOC
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USERNAME=$(gh api /user -q .login)
          echo "User: $USERNAME"
          
          # Simple count of this repo first
          lines=$(tokei . -o json | jq -r '.Total.code // 0')
          echo "This repo has $lines lines"
          
          # Format
          if [ $lines -ge 1000000 ]; then
            formatted="$((lines/1000000))M+"
          elif [ $lines -ge 1000 ]; then  
            formatted="$((lines/1000))K+"
          else
            formatted="${lines}+"
          fi
          
          # Update file
          echo "{
            \"lines_of_code\": $lines,
            \"repositories\": 1,
            \"last_updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
            \"formatted\": \"$formatted\"
          }" > stats-simple.json
          
      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats-simple.json
          git diff --staged --quiet || (git commit -m "Update LOC stats" && git push)