name: LOC
on: push
jobs:
  count:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Count
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Quick test - just count this repo
          lines=$(find . -name "*.js" -o -name "*.html" -o -name "*.css" | xargs wc -l | tail -1 | awk '{print $1}')
          echo "Lines: $lines"
          
          # Update stats
          echo "{\"lines_of_code\": $lines, \"repositories\": 1, \"last_updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"formatted\": \"${lines}+\"}" > stats-simple.json
          
          # Commit
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats-simple.json
          git diff --staged --quiet || (git commit -m "Update LOC" && git push)