name: LOC
on: push
jobs:
  count:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Count
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use hardcoded username since we know this is murr2k's repo
          USERNAME="murr2k"
          echo "Counting for $USERNAME..."
          
          # Clone and count each repo
          total=0
          count=0
          
          # Get public repos without auth, filter out forks
          repos=$(curl -s "https://api.github.com/users/$USERNAME/repos?type=owner&per_page=100")
          
          # Parse JSON to get non-forked repo names
          for repo in $(echo "$repos" | grep -B2 '"fork": false' | grep '"name"' | cut -d'"' -f4); do
            echo "Processing $repo..."
            if git clone -q --depth 1 "https://github.com/$USERNAME/$repo" "/tmp/$repo" 2>/dev/null; then
              lines=$(find "/tmp/$repo" -type f \( -name "*.js" -o -name "*.ts" -o -name "*.py" -o -name "*.java" -o -name "*.go" -o -name "*.rb" -o -name "*.php" -o -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.cs" -o -name "*.swift" -o -name "*.kt" -o -name "*.rs" -o -name "*.html" -o -name "*.css" -o -name "*.scss" -o -name "*.jsx" -o -name "*.tsx" -o -name "*.vue" \) 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo "0")
              total=$((total + lines))
              rm -rf "/tmp/$repo"
            fi
            count=$((count + 1))
          done
          
          echo "Total: $total lines in $count repos"
          
          # Format
          if [ $total -ge 1000000 ]; then
            formatted="$((total/1000000))M+"
          elif [ $total -ge 1000 ]; then
            formatted="$((total/1000))K+"
          else
            formatted="${total}+"
          fi
          
          # Update stats
          echo "{\"lines_of_code\": $total, \"repositories\": $count, \"last_updated\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"formatted\": \"$formatted\"}" > stats-simple.json
          
          # Commit
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats-simple.json
          git diff --staged --quiet || (git commit -m "Update LOC" && git push)