name: Simple LOC Counter

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  count:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Count and Update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # For now, just count this repository's lines
          # Using find and wc as a simple fallback
          lines=$(find . -type f \( -name "*.js" -o -name "*.html" -o -name "*.css" -o -name "*.py" -o -name "*.yml" \) -not -path "./node_modules/*" -not -path "./.git/*" | xargs wc -l | tail -1 | awk '{print $1}')
          
          echo "Found $lines lines of code"
          
          # Format
          if [ $lines -ge 1000000 ]; then
            formatted="$((lines/1000000))M+"
          elif [ $lines -ge 1000 ]; then  
            formatted="$((lines/1000))K+"
          else
            formatted="${lines}+"
          fi
          
          # Update file
          cat > stats-simple.json << EOF
{
  "lines_of_code": $lines,
  "repositories": 1,
  "last_updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "formatted": "$formatted"
}
EOF
          
          # Commit if changed
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats-simple.json
          git diff --staged --quiet || (git commit -m "📊 Update LOC stats: $formatted" && git push)