name: Update LOC
on: 
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Counting lines..."
          lines=$(find . -name "*.js" -o -name "*.html" -o -name "*.css" | xargs wc -l | tail -1 | awk '{print $1}')
          echo "Found $lines lines"
          formatted="${lines}+"
          if [ $lines -ge 1000 ]; then
            formatted="$((lines/1000))K+"
          fi
          cat > stats-simple.json << EOF
{
  "lines_of_code": $lines,
  "repositories": 1,
  "last_updated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "formatted": "$formatted"
}
EOF
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add stats-simple.json || true
          git commit -m "Update stats" || true
          git push || true